name: Docker Image CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 13 * * *'
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run the Docker image
      run: docker build . --file Dockerfile --tag bad:$(date +%s)

